name: Matrix

on: [push]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        browser: [Chrome, Edge, Firefox]
    steps:
    - run: echo Hello World!
