name: Matrix

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build.sh

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        browser: [Chrome, Edge, Firefox]
    steps:
    - run: ./executeBrowserTest --browser=${{ matrix.browser }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - run: ./uploadRelease.sh
